export const ADD_PROPERTY_REQUEST = "ADD_PROPERTY_REQUEST"
export const ADD_PROPERTY_SUCCESS = "ADD_PROPERTY_SUCCESS"
export const ADD_PROPERTY_FAIL = "ADD_PROPERTY_FAIL"

export const LIST_PROPERTY_REQUEST = "LIST_PROPERTY_REQUEST"
export const LIST_PROPERTY_SUCCESS = "LIST_PROPERTY_SUCCESS"
export const LIST_PROPERTY_FAIL = "LIST_PROPERTY_FAIL"

export const PROPERTY_DETAILS_REQUEST = "PROPERTY_DETAILS_REQUEST"
export const PROPERTY_DETAILS_SUCCESS = "PROPERTY_DETAILS_SUCCESS"
export const PROPERTY_DETAILS_FAIL = "PROPERTY_DETAILS_FAIL"


export const LIST_USER_SPECIFIC_PROPERTY_REQUEST = "LIST_USER_SPECIFIC_PROPERTY_REQUEST"
export const LIST_USER_SPECIFIC_PROPERTY_SUCCESS = "LIST_USER_SPECIFIC_PROPERTY_SUCCESS"
export const LIST_USER_SPECIFIC_PROPERTY_FAIL = "LIST_USER_SPECIFIC_PROPERTY_FAIL"