const ACCOUNT_CONNECT_SUCCESS = "ACCOUNT_CONNECT_SUCCESS"
const ACCOUNT_CONNECT_FAIL = "ACCOUNT_CONNECT_FAIL"


const SELLER_WALLET_AND_CLONE_ADDRESS_SUCCESS = "SELLER_WALLET_AND_CLONE_ADDRESS_SUCCESS"
const SELLER_WALLET_AND_CLONE_ADDRESS_FAIL = "SELLER_WALLET_AND_CLONE_ADDRESS_FAIL"
// const SELLER_CLONE_ADDRESS = "SELLER_CLONE_ADDRESS"